
// This file has been generated by the GUI designer. Do not modify.
namespace PDVS
{
	public partial class AddParDialog
	{
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ComboBox cmbParametros;
		
		private global::Gtk.Entry entryValor;
		
		private global::Gtk.Button btnCancela;
		
		private global::Gtk.Button btnAdiciona;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PDVS.AddParDialog
			this.Name = "PDVS.AddParDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Adiciona Parametro");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child PDVS.AddParDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Parametro                                                                  Valor");
			this.vbox4.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.cmbParametros = global::Gtk.ComboBox.NewText ();
			this.cmbParametros.WidthRequest = 300;
			this.cmbParametros.Name = "cmbParametros";
			this.hbox2.Add (this.cmbParametros);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cmbParametros]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryValor = new global::Gtk.Entry ();
			this.entryValor.CanFocus = true;
			this.entryValor.Name = "entryValor";
			this.entryValor.IsEditable = true;
			this.entryValor.InvisibleChar = '•';
			this.hbox2.Add (this.entryValor);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entryValor]));
			w4.Position = 1;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Internal child PDVS.AddParDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnCancela = new global::Gtk.Button ();
			this.btnCancela.CanFocus = true;
			this.btnCancela.Name = "btnCancela";
			this.btnCancela.UseUnderline = true;
			this.btnCancela.Label = global::Mono.Unix.Catalog.GetString ("Cancela");
			this.AddActionWidget (this.btnCancela, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.btnCancela]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnAdiciona = new global::Gtk.Button ();
			this.btnAdiciona.CanFocus = true;
			this.btnAdiciona.Name = "btnAdiciona";
			this.btnAdiciona.UseUnderline = true;
			this.btnAdiciona.Label = global::Mono.Unix.Catalog.GetString ("Adiciona");
			this.AddActionWidget (this.btnAdiciona, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.btnAdiciona]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 510;
			this.DefaultHeight = 128;
			this.Show ();
			this.btnAdiciona.Clicked += new global::System.EventHandler (this.OnBtnAdicionaClicked);
		}
	}
}
