
// This file has been generated by the GUI designer. Do not modify.
namespace PDVS
{
	public partial class ConfirmationWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.ComboBox cbmTranstatus;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Button btnApply;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PDVS.ConfirmationWindow
			this.Name = "PDVS.ConfirmationWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ConfirmationWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.BorderWidth = ((uint)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 400;
			this.DefaultHeight = 400;
			// Container child PDVS.ConfirmationWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbmTranstatus = global::Gtk.ComboBox.NewText ();
			this.cbmTranstatus.WidthRequest = 200;
			this.cbmTranstatus.Name = "cbmTranstatus";
			this.fixed1.Add (this.cbmTranstatus);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cbmTranstatus]));
			w1.X = 35;
			w1.Y = 44;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Selecione o status da transação :");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w2.X = 36;
			w2.Y = 15;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnApply = new global::Gtk.Button ();
			this.btnApply.CanFocus = true;
			this.btnApply.Name = "btnApply";
			this.btnApply.UseUnderline = true;
			this.btnApply.Label = global::Mono.Unix.Catalog.GetString ("Aplicar");
			this.fixed1.Add (this.btnApply);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnApply]));
			w3.X = 263;
			w3.Y = 45;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.cbmTranstatus.SelectionReceived += new global::Gtk.SelectionReceivedHandler (this.OnCbmTransactionStatusesSelectionReceived);
			this.cbmTranstatus.SelectionGet += new global::Gtk.SelectionGetHandler (this.OnCbmTranstatusSelectionGet);
			this.btnApply.Clicked += new global::System.EventHandler (this.OnBtnApplyClicked);
		}
	}
}
