
// This file has been generated by the GUI designer. Do not modify.
namespace PDVS
{
	public partial class ConfirmationWindowDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox cmbStTrans;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button btnAplicar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PDVS.ConfirmationWindowDialog
			this.Name = "PDVS.ConfirmationWindowDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Confirmation Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child PDVS.ConfirmationWindowDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Seleciona o status da transação");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.cmbStTrans = global::Gtk.ComboBox.NewText ();
			this.cmbStTrans.Name = "cmbStTrans";
			this.vbox2.Add (this.cmbStTrans);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.cmbStTrans]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child PDVS.ConfirmationWindowDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonCancel]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnAplicar = new global::Gtk.Button ();
			this.btnAplicar.CanDefault = true;
			this.btnAplicar.CanFocus = true;
			this.btnAplicar.Name = "btnAplicar";
			this.btnAplicar.UseUnderline = true;
			this.btnAplicar.Label = global::Mono.Unix.Catalog.GetString ("Aplicar");
			this.AddActionWidget (this.btnAplicar, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.btnAplicar]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 145;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.btnAplicar.Clicked += new global::System.EventHandler (this.OnBtnAplicarClicked);
		}
	}
}
