
// This file has been generated by the GUI designer. Do not modify.
namespace PDVS
{
	public partial class CaptureUserDataDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.ComboBox cmbCaptura;
		
		private global::Gtk.Entry entryMin;
		
		private global::Gtk.Entry entryMax;
		
		private global::Gtk.Button btnCaptura;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PDVS.CaptureUserDataDialog
			this.Name = "PDVS.CaptureUserDataDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Captura dados Pinpad");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child PDVS.CaptureUserDataDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Capturar no Pinpad                                                   Min.                         Max.");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmbCaptura = global::Gtk.ComboBox.NewText ();
			this.cmbCaptura.WidthRequest = 300;
			this.cmbCaptura.Name = "cmbCaptura";
			this.hbox1.Add (this.cmbCaptura);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmbCaptura]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryMin = new global::Gtk.Entry ();
			this.entryMin.WidthRequest = 80;
			this.entryMin.CanFocus = true;
			this.entryMin.Name = "entryMin";
			this.entryMin.IsEditable = true;
			this.entryMin.InvisibleChar = '•';
			this.hbox1.Add (this.entryMin);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryMin]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryMax = new global::Gtk.Entry ();
			this.entryMax.WidthRequest = 80;
			this.entryMax.CanFocus = true;
			this.entryMax.Name = "entryMax";
			this.entryMax.IsEditable = true;
			this.entryMax.InvisibleChar = '•';
			this.hbox1.Add (this.entryMax);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryMax]));
			w5.Position = 2;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Internal child PDVS.CaptureUserDataDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnCaptura = new global::Gtk.Button ();
			this.btnCaptura.CanFocus = true;
			this.btnCaptura.Name = "btnCaptura";
			this.btnCaptura.UseUnderline = true;
			this.btnCaptura.Label = global::Mono.Unix.Catalog.GetString ("Captura");
			this.AddActionWidget (this.btnCaptura, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.btnCaptura]));
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 556;
			this.DefaultHeight = 126;
			this.Show ();
			this.btnCaptura.Clicked += new global::System.EventHandler (this.OnBtnCapturaClicked);
		}
	}
}
